name = "PolyJuMP"
uuid = "ddf597a6-d67e-5340-b84c-e37d84115374"
repo = "https://github.com/JuliaOpt/PolyJuMP.jl.git"
version = "0.3.3"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
MultivariateMoments = "f4abf1af-0426-5881-a0da-e2f168889b5e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
SemialgebraicSets = "8e049039-38e8-557d-ae3a-bc521ccf6204"

[compat]
JuMP = "0.20"
MathOptInterface = "~0.9.1"
MultivariateMoments = "â‰¥ 0.2.1"
MultivariatePolynomials = "~0.3"
SemialgebraicSets = "0.2"
julia = "1"

[extras]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LinearAlgebra", "DynamicPolynomials", "Test"]
